// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: asdr_lex_schneider.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\3\u1f00"+
    "\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u1f00\1\u4a00\1\u1f00\1\u4b00\1\u4c00\2\u1f00\3\u0100"+
    "\1\u4d00\1\u4e00\1\u4f00\12\u1f00\4\u0100\1\u5000\17\u1f00\2\u0100"+
    "\1\u5100\41\u1f00\2\u0100\1\u5200\1\u5300\3\u1f00\1\u5400\27\u0100"+
    "\1\u5500\2\u0100\1\u5600\45\u1f00\1\u0100\1\u5700\1\u5800\11\u1f00"+
    "\1\u5900\24\u1f00\1\u5a00\1\u5b00\1\u1f00\1\u5c00\1\u5d00\1\u5e00"+
    "\1\u5f00\2\u1f00\1\u6000\5\u1f00\1\u6100\7\u1f00\1\u6200\1\u6300"+
    "\4\u1f00\1\u6400\21\u1f00\246\u0100\1\u6500\20\u0100\1\u6600\1\u6700"+
    "\25\u0100\1\u6800\34\u0100\1\u6900\14\u1f00\2\u0100\1\u6a00\u0b05\u1f00"+
    "\1\u6b00\1\u6c00\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\1\1\1\2\1\3\2\4\1\3\16\0\4\5"+
    "\1\2\3\5\1\6\3\5\6\7\1\5\1\7\12\10"+
    "\1\5\1\7\1\5\1\7\3\5\1\11\1\12\1\13"+
    "\1\12\1\14\1\15\7\12\1\16\1\17\2\12\1\20"+
    "\1\12\1\21\6\12\4\5\1\22\1\5\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\12\1\31\1\32\2\12"+
    "\1\33\1\12\1\34\1\35\3\12\1\36\1\37\1\40"+
    "\1\41\1\42\3\12\1\7\1\5\1\7\1\5\6\0"+
    "\1\43\32\0\2\5\4\12\4\5\1\12\2\5\1\0"+
    "\7\5\1\12\4\5\1\12\5\5\27\12\1\5\37\12"+
    "\1\5\u01ca\12\4\5\14\12\16\5\5\12\7\5\1\12"+
    "\1\5\1\12\21\5\160\0\5\12\1\5\2\12\2\5"+
    "\4\12\1\5\1\12\6\5\1\12\1\5\3\12\1\5"+
    "\1\12\1\5\24\12\1\5\123\12\1\5\213\12\1\5"+
    "\5\0\2\5\246\12\1\5\46\12\2\5\1\12\7\5"+
    "\47\12\7\5\1\12\1\5\55\0\1\5\1\0\1\5"+
    "\2\0\1\5\2\0\1\5\1\0\10\5\33\12\5\5"+
    "\3\12\15\5\6\0\5\5\1\12\4\5\13\0\1\5"+
    "\1\0\3\5\53\12\37\0\4\5\2\12\1\0\143\12"+
    "\1\5\1\12\10\0\1\5\6\0\2\12\2\0\1\5"+
    "\4\0\2\12\12\0\3\12\2\5\1\12\17\5\1\0"+
    "\1\12\1\0\36\12\33\0\2\5\131\12\13\0\1\12"+
    "\16\5\12\0\41\12\11\0\2\12\4\5\1\12\5\5"+
    "\26\12\4\0\1\12\11\0\1\12\3\0\1\12\5\0"+
    "\22\5\31\12\3\0\4\5\13\12\65\5\25\12\1\5"+
    "\10\12\26\5\60\0\66\12\3\0\1\12\22\0\1\12"+
    "\7\0\12\12\2\0\2\5\12\0\1\5\20\12\3\0"+
    "\1\5\10\12\2\5\2\12\2\5\26\12\1\5\7\12"+
    "\1\5\1\12\3\5\4\12\2\5\1\0\1\12\7\0"+
    "\2\5\2\0\2\5\3\0\1\12\10\5\1\0\4\5"+
    "\2\12\1\5\3\12\2\0\2\5\12\0\4\12\7\5"+
    "\2\12\4\5\3\0\1\5\6\12\4\5\2\12\2\5"+
    "\26\12\1\5\7\12\1\5\2\12\1\5\2\12\1\5"+
    "\2\12\2\5\1\0\1\5\5\0\4\5\2\0\2\5"+
    "\3\0\3\5\1\0\7\5\4\12\1\5\1\12\7\5"+
    "\14\0\3\12\1\0\13\5\3\0\1\5\11\12\1\5"+
    "\3\12\1\5\26\12\1\5\7\12\1\5\2\12\1\5"+
    "\5\12\2\5\1\0\1\12\10\0\1\5\3\0\1\5"+
    "\3\0\2\5\1\12\17\5\2\12\2\0\2\5\12\0"+
    "\1\5\1\12\7\5\1\12\6\0\1\5\3\0\1\5"+
    "\10\12\2\5\2\12\2\5\26\12\1\5\7\12\1\5"+
    "\2\12\1\5\5\12\2\5\1\0\1\12\7\0\2\5"+
    "\2\0\2\5\3\0\10\5\2\0\4\5\2\12\1\5"+
    "\3\12\2\0\2\5\12\0\1\5\1\12\20\5\1\0"+
    "\1\12\1\5\6\12\3\5\3\12\1\5\4\12\3\5"+
    "\2\12\1\5\1\12\1\5\2\12\3\5\2\12\3\5"+
    "\3\12\3\5\14\12\4\5\5\0\3\5\3\0\1\5"+
    "\4\0\2\5\1\12\6\5\1\0\16\5\12\0\11\5"+
    "\1\12\6\5\4\0\1\5\10\12\1\5\3\12\1\5"+
    "\27\12\1\5\20\12\3\5\1\12\7\0\1\5\3\0"+
    "\1\5\4\0\7\5\2\0\1\5\3\12\5\5\2\12"+
    "\2\0\2\5\12\0\20\5\1\12\3\0\1\5\10\12"+
    "\1\5\3\12\1\5\27\12\1\5\12\12\1\5\5\12"+
    "\2\5\1\0\1\12\7\0\1\5\3\0\1\5\4\0"+
    "\7\5\2\0\7\5\1\12\1\5\2\12\2\0\2\5"+
    "\12\0\1\5\2\12\15\5\4\0\1\5\10\12\1\5"+
    "\3\12\1\5\51\12\2\0\1\12\7\0\1\5\3\0"+
    "\1\5\4\0\1\12\5\5\3\12\1\0\7\5\3\12"+
    "\2\0\2\5\12\0\12\5\6\12\2\5\2\0\1\5"+
    "\22\12\3\5\30\12\1\5\11\12\1\5\1\12\2\5"+
    "\7\12\3\5\1\0\4\5\6\0\1\5\1\0\1\5"+
    "\10\0\6\5\12\0\2\5\2\0\15\5\60\12\1\0"+
    "\2\12\7\0\4\5\10\12\10\0\1\5\12\0\47\5"+
    "\2\12\1\5\1\12\2\5\2\12\1\5\1\12\2\5"+
    "\1\12\6\5\4\12\1\5\7\12\1\5\3\12\1\5"+
    "\1\12\1\5\1\12\2\5\2\12\1\5\4\12\1\0"+
    "\2\12\6\0\1\5\2\0\1\12\2\5\5\12\1\5"+
    "\1\12\1\5\6\0\2\5\12\0\2\5\4\12\40\5"+
    "\1\12\27\5\2\0\6\5\12\0\13\5\1\0\1\5"+
    "\1\0\1\5\1\0\4\5\2\0\10\12\1\5\44\12"+
    "\4\5\24\0\1\5\2\0\5\12\13\0\1\5\44\0"+
    "\11\5\1\0\71\5\53\12\24\0\1\12\12\0\6\5"+
    "\6\12\4\0\4\12\3\0\1\12\3\0\2\12\7\0"+
    "\3\12\4\0\15\12\14\0\1\12\17\0\2\5\46\12"+
    "\1\5\1\12\5\5\1\12\2\5\53\12\1\5\115\12"+
    "\1\5\4\12\2\5\7\12\1\5\1\12\1\5\4\12"+
    "\2\5\51\12\1\5\4\12\2\5\41\12\1\5\4\12"+
    "\2\5\7\12\1\5\1\12\1\5\4\12\2\5\17\12"+
    "\1\5\71\12\1\5\4\12\2\5\103\12\2\5\3\0"+
    "\40\5\20\12\20\5\126\12\2\5\6\12\3\5\u016c\12"+
    "\2\5\21\12\1\5\32\12\5\5\113\12\3\5\13\12"+
    "\7\5\15\12\1\5\4\12\3\0\13\5\22\12\3\0"+
    "\13\5\22\12\2\0\14\5\15\12\1\5\3\12\1\5"+
    "\2\0\14\5\64\12\40\0\3\5\1\12\3\5\2\12"+
    "\1\0\2\5\12\0\41\5\4\0\1\5\12\0\6\5"+
    "\130\12\10\5\5\12\2\0\42\12\1\0\1\12\5\5"+
    "\106\12\12\5\37\12\1\5\14\0\4\5\14\0\12\5"+
    "\12\0\36\12\2\5\5\12\13\5\54\12\4\5\32\12"+
    "\6\5\12\0\46\5\27\12\5\0\4\5\65\12\12\0"+
    "\1\5\35\0\2\5\13\0\6\5\12\0\15\5\1\12"+
    "\10\5\16\0\102\5\5\0\57\12\21\0\7\12\4\5"+
    "\12\0\21\5\11\0\14\5\3\0\36\12\15\0\2\12"+
    "\12\0\54\12\16\0\14\5\44\12\24\0\10\5\12\0"+
    "\3\5\3\12\12\0\44\12\2\5\11\12\107\5\3\0"+
    "\1\5\25\0\4\12\1\0\4\12\3\0\2\12\3\0"+
    "\6\5\300\12\72\0\1\5\5\0\26\12\2\5\6\12"+
    "\2\5\46\12\2\5\6\12\2\5\10\12\1\5\1\12"+
    "\1\5\1\12\1\5\1\12\1\5\37\12\2\5\65\12"+
    "\1\5\7\12\1\5\1\12\3\5\3\12\1\5\7\12"+
    "\3\5\4\12\2\5\6\12\4\5\15\12\5\5\3\12"+
    "\1\5\7\12\16\5\5\0\30\5\2\4\5\0\20\5"+
    "\2\12\23\5\1\12\13\5\5\0\1\5\12\0\1\5"+
    "\1\12\15\5\1\12\20\5\15\12\3\5\40\12\20\5"+
    "\15\0\4\5\1\0\3\5\14\0\21\5\1\12\4\5"+
    "\1\12\2\5\12\12\1\5\1\12\3\5\5\12\6\5"+
    "\1\12\1\5\1\12\1\5\1\12\1\5\4\12\1\5"+
    "\13\12\2\5\4\12\5\5\5\12\4\5\1\12\21\5"+
    "\51\12\u0177\5\57\12\1\5\57\12\1\5\205\12\6\5"+
    "\4\12\3\0\2\12\14\5\46\12\1\5\1\12\5\5"+
    "\1\12\2\5\70\12\7\5\1\12\17\5\1\0\27\12"+
    "\11\5\7\12\1\5\7\12\1\5\7\12\1\5\7\12"+
    "\1\5\7\12\1\5\7\12\1\5\7\12\1\5\7\12"+
    "\1\5\40\0\57\5\1\12\325\5\3\12\31\5\11\12"+
    "\6\0\1\5\5\12\2\5\5\12\4\5\126\12\2\5"+
    "\2\0\2\5\3\12\1\5\132\12\1\5\4\12\5\5"+
    "\52\12\2\5\136\12\21\5\33\12\65\5\306\12\112\5"+
    "\353\12\25\5\215\12\103\5\56\12\2\5\15\12\3\5"+
    "\20\12\12\0\2\12\24\5\57\12\1\0\4\5\12\0"+
    "\1\5\37\12\2\0\120\12\2\0\45\5\11\12\2\5"+
    "\147\12\2\5\44\12\1\5\10\12\77\5\13\12\1\0"+
    "\3\12\1\0\4\12\1\0\27\12\5\0\20\5\1\12"+
    "\7\5\64\12\14\5\2\0\62\12\22\0\12\5\12\0"+
    "\6\5\22\0\6\12\3\5\1\12\1\5\1\12\2\5"+
    "\12\0\34\12\10\0\2\5\27\12\15\0\14\5\35\12"+
    "\3\5\4\0\57\12\16\0\16\5\1\12\12\0\6\5"+
    "\5\12\1\0\12\12\12\0\5\12\1\5\51\12\16\0"+
    "\11\5\3\12\1\0\10\12\2\0\2\5\12\0\6\5"+
    "\27\12\3\5\1\12\3\0\62\12\1\0\1\12\3\0"+
    "\2\12\2\0\5\12\2\0\1\12\1\0\1\12\30\5"+
    "\3\12\2\5\13\12\5\0\2\5\3\12\2\0\12\5"+
    "\6\12\2\5\6\12\2\5\6\12\11\5\7\12\1\5"+
    "\7\12\1\5\53\12\1\5\12\12\12\5\163\12\10\0"+
    "\1\5\2\0\2\5\12\0\6\5\244\12\14\5\27\12"+
    "\4\5\61\12\4\5\u0100\4\156\12\2\5\152\12\46\5"+
    "\7\12\14\5\5\12\5\5\1\12\1\0\12\12\1\5"+
    "\15\12\1\5\5\12\1\5\1\12\1\5\2\12\1\5"+
    "\2\12\1\5\154\12\41\5\153\12\22\5\100\12\2\5"+
    "\66\12\50\5\15\12\3\5\20\0\20\5\20\0\3\5"+
    "\2\12\30\5\3\12\31\5\1\12\6\5\5\12\1\5"+
    "\207\12\2\5\1\0\4\5\1\12\13\5\12\0\7\5"+
    "\32\12\4\5\1\12\1\5\32\12\13\5\131\12\3\5"+
    "\6\12\2\5\6\12\2\5\6\12\2\5\3\12\3\5"+
    "\2\12\3\5\2\12\22\5\3\0\4\5\14\12\1\5"+
    "\32\12\1\5\23\12\1\5\2\12\1\5\17\12\2\5"+
    "\16\12\42\5\173\12\105\5\65\12\210\5\1\0\202\5"+
    "\35\12\3\5\61\12\17\5\1\0\37\5\40\12\15\5"+
    "\36\12\5\5\46\12\5\0\5\5\36\12\2\5\44\12"+
    "\4\5\10\12\1\5\5\12\52\5\236\12\2\5\12\0"+
    "\6\5\44\12\4\5\44\12\4\5\50\12\10\5\64\12"+
    "\234\5\67\12\11\5\26\12\12\5\10\12\230\5\6\12"+
    "\2\5\1\12\1\5\54\12\1\5\2\12\3\5\1\12"+
    "\2\5\27\12\12\5\27\12\11\5\37\12\101\5\23\12"+
    "\1\5\2\12\12\5\26\12\12\5\32\12\106\5\70\12"+
    "\6\5\2\12\100\5\1\12\3\0\1\5\2\0\5\5"+
    "\4\0\4\12\1\5\3\12\1\5\33\12\4\5\3\0"+
    "\4\5\1\0\40\5\35\12\3\5\35\12\43\5\10\12"+
    "\1\5\34\12\2\0\31\5\66\12\12\5\26\12\12\5"+
    "\23\12\15\5\22\12\156\5\111\12\67\5\63\12\15\5"+
    "\63\12\15\5\3\0\65\12\17\0\37\5\12\0\17\5"+
    "\4\0\55\12\13\0\2\5\1\0\22\5\31\12\7\5"+
    "\12\0\6\5\3\0\44\12\16\0\1\5\12\0\20\5"+
    "\43\12\1\0\2\5\1\12\11\5\3\0\60\12\16\0"+
    "\4\12\5\5\3\0\3\5\12\0\1\12\1\5\1\12"+
    "\43\5\22\12\1\5\31\12\14\0\6\5\1\0\101\5"+
    "\7\12\1\5\1\12\1\5\4\12\1\5\17\12\1\5"+
    "\12\12\7\5\57\12\14\0\5\5\12\0\6\5\4\0"+
    "\1\5\10\12\2\5\2\12\2\5\26\12\1\5\7\12"+
    "\1\5\2\12\1\5\5\12\2\5\1\0\1\12\7\0"+
    "\2\5\2\0\2\5\3\0\2\5\1\12\6\5\1\0"+
    "\5\5\5\12\2\0\2\5\7\0\3\5\5\0\213\5"+
    "\65\12\22\0\4\12\5\5\12\0\46\5\60\12\24\0"+
    "\2\12\1\5\1\12\10\5\12\0\246\5\57\12\7\0"+
    "\2\5\11\0\27\5\4\12\2\0\42\5\60\12\21\0"+
    "\3\5\1\12\13\5\12\0\46\5\53\12\15\0\10\5"+
    "\12\0\66\5\32\12\3\5\17\0\4\5\12\0\u0166\5"+
    "\100\12\12\0\25\5\2\12\12\0\50\12\7\0\1\12"+
    "\4\0\10\5\1\0\10\5\1\12\13\0\50\12\2\5"+
    "\4\12\20\0\46\5\71\12\7\5\11\12\1\5\45\12"+
    "\10\0\1\5\10\0\1\12\17\5\12\0\30\5\36\12"+
    "\2\5\26\0\1\5\16\0\111\5\7\12\1\5\2\12"+
    "\1\5\46\12\6\0\3\5\1\0\1\5\2\0\1\5"+
    "\7\0\1\12\1\0\10\5\12\0\246\5\232\12\146\5"+
    "\157\12\21\5\304\12\274\5\57\12\321\5\107\12\271\5"+
    "\71\12\7\5\37\12\1\5\12\0\146\5\36\12\2\5"+
    "\5\0\13\5\60\12\7\0\11\5\4\12\14\5\12\0"+
    "\11\5\25\12\5\5\23\12\160\5\105\12\13\5\1\12"+
    "\56\0\20\5\4\0\15\12\100\5\2\12\36\5\355\12"+
    "\23\5\363\12\15\5\37\12\121\5\u018c\12\4\5\153\12"+
    "\5\5\15\12\3\5\11\12\7\5\12\12\3\5\2\0"+
    "\1\5\4\0\301\5\5\0\3\5\26\0\2\5\7\0"+
    "\36\5\4\0\224\5\3\0\273\5\125\12\1\5\107\12"+
    "\1\5\2\12\2\5\1\12\2\5\2\12\2\5\4\12"+
    "\1\5\14\12\1\5\1\12\1\5\7\12\1\5\101\12"+
    "\1\5\4\12\2\5\10\12\1\5\7\12\1\5\34\12"+
    "\1\5\4\12\1\5\5\12\1\5\1\12\3\5\7\12"+
    "\1\5\u0154\12\2\5\31\12\1\5\31\12\1\5\37\12"+
    "\1\5\31\12\1\5\37\12\1\5\31\12\1\5\37\12"+
    "\1\5\31\12\1\5\37\12\1\5\31\12\1\5\10\12"+
    "\2\5\151\0\4\5\62\0\10\5\1\0\16\5\1\0"+
    "\26\5\5\0\1\5\17\0\120\5\7\0\1\5\21\0"+
    "\2\5\7\0\1\5\2\0\1\5\5\0\325\5\305\12"+
    "\13\5\7\0\51\5\104\12\7\0\5\5\12\0\246\5"+
    "\4\12\1\5\33\12\1\5\2\12\1\5\1\12\2\5"+
    "\1\12\1\5\12\12\1\5\4\12\1\5\1\12\1\5"+
    "\1\12\6\5\1\12\4\5\1\12\1\5\1\12\1\5"+
    "\1\12\1\5\3\12\1\5\2\12\1\5\1\12\2\5"+
    "\1\12\1\5\1\12\1\5\1\12\1\5\1\12\1\5"+
    "\1\12\1\5\2\12\1\5\1\12\2\5\4\12\1\5"+
    "\7\12\1\5\4\12\1\5\4\12\1\5\1\12\1\5"+
    "\12\12\1\5\21\12\5\5\3\12\1\5\5\12\1\5"+
    "\21\12\104\5\327\12\51\5\65\12\13\5\336\12\2\5"+
    "\u0182\12\16\5\u0131\12\37\5\36\12\343\5\1\0\36\5"+
    "\140\0\200\5\360\0\20\5";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\11\3\1\0"+
    "\4\3\1\6\10\3\1\7\5\3\1\10\1\11\1\12"+
    "\4\3\1\13\2\3\1\14\1\3\1\15\2\3\1\16"+
    "\1\17";

  private static int [] zzUnpackAction() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\44\0\220\0\264\0\330"+
    "\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8"+
    "\0\u021c\0\u0240\0\u0264\0\u0288\0\264\0\u02ac\0\u02d0\0\u02f4"+
    "\0\u0318\0\u033c\0\u0360\0\u0384\0\u03a8\0\264\0\u03cc\0\u03f0"+
    "\0\u0414\0\u0438\0\u045c\0\264\0\264\0\264\0\u0480\0\u04a4"+
    "\0\u04c8\0\u04ec\0\264\0\u0510\0\u0534\0\264\0\u0558\0\264"+
    "\0\u057c\0\u05a0\0\264\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\0\1\2\1\4\1\5\1\6\13\7"+
    "\1\10\1\7\1\11\1\12\1\13\1\7\1\14\6\7"+
    "\1\15\1\16\46\0\3\3\40\0\2\7\4\0\1\7"+
    "\1\0\11\7\1\17\22\7\3\20\2\0\3\20\1\6"+
    "\32\20\1\0\2\7\4\0\1\7\1\0\36\7\4\0"+
    "\1\7\1\0\25\7\1\21\10\7\4\0\1\7\1\0"+
    "\25\7\1\22\10\7\4\0\1\7\1\0\23\7\1\23"+
    "\12\7\4\0\1\7\1\0\30\7\1\24\5\7\4\0"+
    "\1\7\1\0\20\7\1\25\3\7\1\26\11\7\4\0"+
    "\1\7\1\0\25\7\1\27\10\7\4\0\1\7\1\0"+
    "\21\7\1\30\14\7\4\0\1\7\1\0\10\7\1\31"+
    "\23\7\10\0\1\6\33\0\2\7\4\0\1\7\1\0"+
    "\25\7\1\32\10\7\4\0\1\7\1\0\30\7\1\33"+
    "\5\7\4\0\1\7\1\0\26\7\1\34\7\7\4\0"+
    "\1\7\1\0\24\7\1\35\11\7\4\0\1\7\1\0"+
    "\27\7\1\36\6\7\4\0\1\7\1\0\22\7\1\37"+
    "\13\7\4\0\1\7\1\0\22\7\1\40\13\7\4\0"+
    "\1\7\1\0\1\7\1\41\34\7\4\0\1\7\1\0"+
    "\23\7\1\42\12\7\4\0\1\7\1\0\14\7\1\43"+
    "\21\7\4\0\1\7\1\0\17\7\1\44\16\7\4\0"+
    "\1\7\1\0\15\7\1\45\20\7\4\0\1\7\1\0"+
    "\16\7\1\46\17\7\4\0\1\7\1\0\23\7\1\47"+
    "\12\7\4\0\1\7\1\0\3\7\1\50\32\7\4\0"+
    "\1\7\1\0\17\7\1\51\16\7\4\0\1\7\1\0"+
    "\23\7\1\52\12\7\4\0\1\7\1\0\17\7\1\53"+
    "\16\7\4\0\1\7\1\0\4\7\1\54\31\7\4\0"+
    "\1\7\1\0\13\7\1\55\22\7\4\0\1\7\1\0"+
    "\17\7\1\56\16\7\4\0\1\7\1\0\12\7\1\57"+
    "\23\7\4\0\1\7\1\0\24\7\1\60\11\7\4\0"+
    "\1\7\1\0\7\7\1\61\26\7\4\0\1\7\1\0"+
    "\5\7\1\62\1\63\27\7\4\0\1\7\1\0\5\7"+
    "\1\64\26\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1476];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\12\1\1\0\44\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private AsdrSchneider yyparser;

  public Yylex(java.io.Reader r, AsdrSchneider yyparser) {
    this(r);
    this.yyparser = yyparser;
  }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Erro lexico: caracter invalido: <" + yytext() + ">");
            }
            // fall through
          case 16: break;
          case 2:
            { 
            }
            // fall through
          case 17: break;
          case 3:
            { return AsdrSchneider.IDENT;
            }
            // fall through
          case 18: break;
          case 4:
            { return yytext().charAt(0);
            }
            // fall through
          case 19: break;
          case 5:
            { return AsdrSchneider.NUM;
            }
            // fall through
          case 20: break;
          case 6:
            { return AsdrSchneider.IF;
            }
            // fall through
          case 21: break;
          case 7:
            { return AsdrSchneider.INT;
            }
            // fall through
          case 22: break;
          case 8:
            { return AsdrSchneider.ELSE;
            }
            // fall through
          case 23: break;
          case 9:
            { return AsdrSchneider.FUNC;
            }
            // fall through
          case 24: break;
          case 10:
            { return AsdrSchneider.VOID;
            }
            // fall through
          case 25: break;
          case 11:
            { return AsdrSchneider.WHILE;
            }
            // fall through
          case 26: break;
          case 12:
            { return AsdrSchneider.DOUBLE;
            }
            // fall through
          case 27: break;
          case 13:
            { return AsdrSchneider.BOOL;
            }
            // fall through
          case 28: break;
          case 14:
            { yyparser.setDebug(true);
            }
            // fall through
          case 29: break;
          case 15:
            { yyparser.setDebug(false);
            }
            // fall through
          case 30: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
